## # 예외처리

#### 자바 프로그램 오류

- **에러**
  - 코드에 의해서 수습될 수 없는 심각한 오류
  - 컴파일 에러, 런타임 에러, 논리적 에러(의도와 다르게 동작)
  - ex: OutOfMemoryError, StackOverflowError
- **예외**
  - 코드에 의해 수습될 수 있는 다소 미약한 오류



#### 예외 클래스의 계층구조

- 모든 예외의 최고 조상은 _Exception 클래스_

  1. ***RuntimeException 클래스와 그 자손 = unchecked 예외***

     ❖ 프로그래머의 실수로 발생

     ❖ 예외 처리를 하지 않아도 컴파일은 가능하되, 실행 시 프로그램이 비정상적으로 종료됨

     ❖ ex: NullPointerException, ArrayIndexOutOfBoundsException, ArithmeticException 등

  2. ***RuntimeException 클래스 자손이 아니면서 Exception 클래스 자손인 클래스 = checked 예외***

     ❖ 사용자의 실수 같은 외적 요인으로 발생

     ❖ 반드시 예외 처리를 해야 컴파일이 가능

     ❖ ex: FileNotFoundException, ClassNotFoundException, DataFormatException 등



#### 예외 처리

- 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성

  > try {
  >
  > ​	// 예외가 발생할 가능성이 있는 문장들
  >
  > } catch (Exception1 e1) {
  >
  > ​	// Exception1이 발생했을 때 처리하기 위한 문장
  >
  > } catch (Exception2 e2) {
  >
  > ​	// Exception2가 발생했을 때 처리하기 위한 문장
  >
  > }

  - **catch (처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언) { 처리 내용 }** 

    - 예외가 발생하면 발생한 예외에 해당하는 클래스의 인스턴스가 생성됨
    - try 블럭에 예외가 발생한 문장이 있으면 처리 가능한 catch 블럭 탐색
    - 생성된 예외 클래스의 인스턴스와 catch 블럭의 괄호 내 참조변수를 비교, 검사 ➤ instanceof 연산자 이용 검사
    - 발생한 예외의 종류와 일치하는 단 한 개의 catch 블럭만 수행
    - try 문에 반환값(return문)이 있으면 catch 블럭에도 반환값(return문)이 있어야 함

  - **멀티 catch 블럭**

    - 여러 catch 블럭을 하나의 catch 블럭으로 합침

    - 연결할 수 있는 예외 클래스의 개수는 무한

    - 조상과 자손 관계의 클래스는 함께 사용할 수 없으며 이 경우 조상 클래스만 사용

    - 실제로 어떤 예외가 발생한 것인지 알 수 없음 ➤ 공통 분모인 조상 예외 클래스에 선언된 멤버만 사용 가능

      > catch (Exception1 | Exception2 | exception3 e) {
      >
      > ​	e.printStackTrace();
      >
      > }

  - **메서드에 예외 선언하기**

    - 메서드의 선언부에 키워드 _throws_를 사용하여 메서드 내부에서 발생할 수 있는 예외를 적어줌

    - 메서드를 사용하기 위해 어떠한 예외들이 처리되어져야 하는지 쉽게 파악 가능

    - 예외가 발생한 메서드에서 예외를 처리하지 않으면 자신을 호출한 메서드로 예외를 넘김

    - 예외가 선언되어 있으면 checked 예외를 try-catch문으로 처리하지 않아도 컴파일 에러가 발생하지 않음

      > void 메서드명() throws Exception1, Exception2, ... ExceptionN { 
      >
      > ​	// 메서드의 내용
      >
      > }



#### 예외 정보

- 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보(_발생원인_)가 담겨 있으며 이를 위한 메서드가 있음
  1. **printStackTrace()** : 예외발생 당시 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력
  2. **getMessage()** : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있음



#### 예외 발생시키기

- 발생시키려는 예외 클래스의 객체를 만든 다음 키워드 _throw_를 이용해서 고의로 예외를 발생시킴

- 예외 클래스의 생성자에 String을 넣어 주면 인스턴스에 메세지로 저장되고 getMessage()로 얻을 수 있음

  > throw new Exception("예외내용")



#### finally 블럭

- 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용

- try - catch 문의 끝에 선택적으로 덧붙여 사용

- 예외가 발생하면 try → catch → finally 순으로 실행

  예외가 발생하지 않으면 try → finally 순으로 실행



#### 사용자 정의 예외

- 필요에 따라 새로운 예외 클래스를 정의하여 사용
- 기존의 Exception 클래스 중 하나를 상속받아 만듦



#### 예외 되던지기

- 예외를 처리한 후 인위적으로 다시 발생시키는 것
- 하나의 예외에 대해서 예외가 발생한 메서드와 호출한 메서드 양쪽에서 처리하도록 할 수 있음



#### 연결된 예외

- 여러 가지 예외를 하나의 큰 분류의 예외로 묶어서 다루기 위해, 발생한 예외를 원인 예외로 등록해서 다시 예외를 발생시킴

- Exception 클래스의 조상인 Throwable 클래스의 메서드 사용

  > Throwable initCause(Throwable cause) // 매개변수로 지정한 예외를 원인 예외로 등록
  >
  > Throwable getCause() // 원인 예외를 반환

- checked 예외를 unchecked 예외로 바꿀 수 있음

  > throw new RuntimeException(throwable cause) // 원인 예외를 등록하는 생성자

